### ISSUE TITLE
Squid https lets everything through

### ISSUE THREAD

**Issue by mgresko** [nearform/aws-proxy-pattern#1]
Thanks for posting this... It appears that he squid configuration allows everything https through.  I was able to resolve by:

```
#ssl_bump terminate step3 all
ssl_bump terminate all
```
Using squid-3.5.20 on amazon linux 2

**Comment by mgresko** [comment]
Further reduced:

```
ssl_bump peek step1 all
ssl_bump splice step2 allowed_https_sites
ssl_bump terminate all
```

**Comment by simoneb** [comment]
This repository is no longer maintained.
